name: animated_count_text
description: A lightweight Flutter widget that smoothly animates numeric text with support for decimals, prefixes, suffixes, and custom curves.
version: 1.1.0

homepage: https://github.com/ashiqu-ali/animated_count_text
repository: https://github.com/ashiqu-ali/animated_count_text
issue_tracker: https://github.com/ashiqu-ali/animated_count_text/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - animation
  - counter
  - animated-text
  - numeric
  - count-up

flutter: